# -*- coding: utf-8 -*-
"""Simple_if_else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HJdobqKayw8Hx9_9WWqonpTGUW-k01wN
"""

a = int(input("First number:"))
b = int(input("Second number:"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile script1
# if a>b:
#   c=a
# else:
#   c=b
# print ("the larger of two no. is - ",c)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile script2
# if a<b:
#   d=a
# else:
#   d=b
# print ("the smaller of two no. is - ",d)
#